name: Release
on:
  push:
    tags:
    - v*
jobs:
  release:
    runs-on: 'ubuntu-latest'
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # # v4.1.7
    - name: Set up JDK
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
        server-id: ossrh
        server-username: CI_DEPLOY_USERNAME
        server-password: CI_DEPLOY_PASSWORD
    - name: Build and Deploy
      run: ./mvnw -B -V -ntp -Dgpg.signer=bc -Prelease deploy
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        MAVEN_GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
